moved api testing after docker image build

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -49,8 +49,9 @@ jobs:
       # -----------------------------
       # Configure AWS credentials
       # -----------------------------
-      # Required for DVC S3 remote
-      # and later for AWS ECR
+      # Required for:
+      # 1. DVC S3 remote
+      # 2. AWS ECR
       # -----------------------------
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4
@@ -116,17 +117,6 @@ jobs:
 
 
       # -----------------------------
-      # Test FastAPI
-      # -----------------------------
-      - name: Run API tests
-        if: success()
-        env:
-          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
-        run: |
-          python -m pytest tests/test_api_endpoint.py
-
-
-      # -----------------------------
       # Login to AWS ECR
       # -----------------------------
       - name: Login to AWS ECR
@@ -171,10 +161,36 @@ jobs:
         if: success()
         run: |
           echo "Waiting for API to start..."
-          sleep 20
+
+          for i in {1..30}; do
+
+            if curl -s --fail http://localhost:8000/health > /dev/null; then
+              echo "API is ready!"
+              exit 0
+            fi
+
+            echo "Waiting... attempt $i"
+            sleep 2
+
+          done
+
+          echo "API failed to start."
 
           echo "Docker container logs:"
           docker logs delivery-api
+
+          exit 1
+
+
+      # -----------------------------
+      # Test FastAPI prediction endpoint
+      # -----------------------------
+      - name: Run API tests
+        if: success()
+        env:
+          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
+        run: |
+          python -m pytest tests/test_api_endpoint.py
 
 
       # -----------------------------
@@ -208,7 +224,7 @@ jobs:
 
 
       # -----------------------------
-      # Push Docker image to ECR
+      # Push Docker image to AWS ECR
       # -----------------------------
       - name: Push Docker image to AWS ECR
         if: success()
